[package]
name = "naive-bayes-hoeffding-trees-rust-implementation"
version = "0.1.0"
edition = "2024"

[dependencies]
tempfile = "3.20.0"
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
